### ISSUE TITLE
apply_force has no effect

### ISSUE THREAD

**Issue by eldyer** [rustsim/nphysics#107]
Calling `apply_force` on a body seems to have no effect.

It appears that this method modifies the `external_forces` value of a body - which is set to zero in the `step` method (as part of `clear_dynamics`).

**Comment by eldyer** [comment]
Update: `apply_force` works fine when called inside a `ForceGenerator` implementation. So I guess you aren't supposed to call it directly on a body? In this case this issue can be closed.

**Comment by sebcrozet** [comment]
Sorry for the late answer, I somehow did not see the first notification.

Yes, `apply_force` does not work outside of a `ForceGenerator` because all forces are reset at the beginning of each timestep as you found out. Though I think it would be useful to make `apply_force` have an effect even when called outside of the force generator, at least to avoid people getting confused.
